export const START_SIGNUP = 'START_SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const START_SECOND_SIGNUP = 'START_SECOND_SIGNUP';
export const SIGNUP_SECOND_SUCCESS = 'SIGNUP_SECOND_SUCCESS';
export const SIGNUP_SECOND_FAIL = 'SIGNUP_SECOND_FAIL';

export const START_SIGNIN = 'START_SIGNIN';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAIL = 'SIGNUP_FAIL';

export const AUTHENTICATE = 'AUTHENTICATE';
export const AUTHENTICATE_FAIL = 'AUTHENTICATE_FAIL';
export const AUTHENTICATE_START = 'AUTHENTICATE_START';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_START = 'EDIT_USER_START';
export const EDIT_USER_FAIL = 'EDIT_USER_FAIL';

export const EDIT_USER_IMAGE_SUCCESS = 'EDIT_USER_IMAGE_SUCCESS';
export const EDIT_USER_IMAGE_START = 'EDIT_USER_IMAGE_START';
export const EDIT_USER_IMAGE_FAIL = 'EDIT_USER_IMAGE_FAIL';

export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_START = 'CHANGE_PASSWORD_START';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';
export const RESET = 'RESET';

export const UPDATE_BANK_START = 'UPDATE_BANK_START';
export const UPDATE_BANK_SUCCESS = 'UPDATE_BANK_SUCCESS';
export const UPDATE_BANK_FAIL = 'UPDATE_BANK_FAIL';

export const FETCH_BANK_START = 'FETCH_BANK_START';
export const FETCH_BANK_SUCCESS = 'FETCH_BANK_SUCCESS';
export const FETCH_BANK_FAIL = 'FETCH_BANK_FAIL';

export const ADD_STAFF_START = 'ADD_STAFF_START';
export const ADD_STAFF_SUCCESS = 'ADD_STAFF_SUCCESS';
export const ADD_STAFF_FAIL = 'ADD_STAFF_FAIL';

export const FETCH_STAFF_START = 'FETCH_STAFF_START';
export const FETCH_STAFF_SUCCESS = 'FETCH_STAFF_SUCCESS';
export const FETCH_STAFF_FAIL = 'FETCH_STAFF_FAIL';

export const DELETE_STAFF_START = 'DELETE_STAFF_START';
export const DELETE_STAFF_SUCCESS = 'DELETE_STAFF_SUCCESS';
export const DELETE_STAFF_FAIL = 'DELETE_STAFF_FAIL';

export const EDIT_STAFF_START = 'EDIT_STAFF_START';
export const EDIT_STAFF_SUCCESS = 'EDIT_STAFF_SUCCESS';
export const EDIT_STAFF_FAIL = 'EDIT_STAFF_FAIL';
